version: "3.9"

services:
  client:
    container_name: client
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      ORIGIN: "http://localhost:3000"

# networks:
#   default:
#     name: cloudflare
#     external: true