version: '3.8'

services:
  postgres:
    container_name: test-roman-postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  nxginx:
    container_name: test-roman-nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - "3050:80"

  api:
    container_name: test-roman-api
    restart: always
    build:
      dockerfile: Dockerfile
      context: './api'
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - '3001:3000'

  client:
    container_name: test-roman-client
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    depends_on:
      - postgres
    volumes:
      - ./client/:/app
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"

volumes:
  pg_data:
